### ISSUE TITLE
考虑竖直方向上的空气阻力来适应大仰角的情况

### ISSUE THREAD

**Issue by JellyfishKnight** [CodeAlanqian/SolveTrajectory#4]
目前来说这个方案对于联盟赛的方案来说确实能够完美地完成任务，但是在对抗赛中具有很多的起伏地形和目标，例如前哨站和环高。在这种情况下假如我们击打不在一个平面的目标，实测这套算法在不加外部补偿的时候不能够很好地适应。是否应该考虑竖直方向的空气阻力来补偿这方面的不足？🧐

**Comment by CodeAlanqian** [comment]
是的，在UC中确实要考虑一下竖直方向上的空气阻力。但是我目前还没有更新的打算，你可以参考[RMOSS弹道模型](https://robomaster-oss.github.io/rmoss_tutorials/#/rmoss_core/rmoss_projectile_motion/projectile_motion_iteration?id=%e4%ba%94%e3%80%81%e5%ae%8c%e5%85%a8%e7%a9%ba%e6%b0%94%e9%98%bb%e5%8a%9b%e6%a8%a1%e5%9e%8b)去修正

**Comment by JellyfishKnight** [comment]
> 是的，在UC中确实要考虑一下竖直方向上的空气阻力。但是我目前还没有更新的打算，你可以参考[RMOSS弹道模型](https://robomaster-oss.github.io/rmoss_tutorials/#/rmoss_core/rmoss_projectile_motion/projectile_motion_iteration?id=%e4%ba%94%e3%80%81%e5%ae%8c%e5%85%a8%e7%a9%ba%e6%b0%94%e9%98%bb%e5%8a%9b%e6%a8%a1%e5%9e%8b)去修正

感谢指路
